const linup = [
	{"day": "Wednesday 10. 6.", "stage": "Mastercard Stage", "start": "13:40", "end": "14:25", "band_name": "MAGNOLIA PARK"},
	{"day": "Wednesday 10. 6.", "stage": "Mastercard Stage", "start": "15:35", "end": "16:35", "band_name": "THE WOMBATS"},
	{"day": "Wednesday 10. 6.", "stage": "Mastercard Stage", "start": "18:10", "end": "19:25", "band_name": "THE PRETTY RECKLESS"},
	{"day": "Wednesday 10. 6.", "stage": "Mastercard Stage", "start": "21:30", "end": "23:00", "band_name": "GORILLAZ"},
	{"day": "Wednesday 10. 6.", "stage": "Rock for People Stage", "start": "12:50", "end": "13:35", "band_name": "WE CAME AS ROMANS"},
	{"day": "Wednesday 10. 6.", "stage": "Rock for People Stage", "start": "14:30", "end": "15:30", "band_name": "BLOODYWOOD"},
	{"day": "Wednesday 10. 6.", "stage": "Rock for People Stage", "start": "16:40", "end": "17:55", "band_name": "MEGADETH"},
	{"day": "Wednesday 10. 6.", "stage": "Rock for People Stage", "start": "19:40", "end": "21:10", "band_name": "ELECTRIC CALLBOY"},
	{"day": "Wednesday 10. 6.", "stage": "E2 Stage", "start": "11:30", "end": "12:15", "band_name": "SPECIAL GUEST BY MASTERCARD"},
	{"day": "Wednesday 10. 6.", "stage": "E2 Stage", "start": "13:05", "end": "13:50", "band_name": "KUBLAI KHAN TX"},
	{"day": "Wednesday 10. 6.", "stage": "E2 Stage", "start": "14:45", "end": "15:30", "band_name": "VOILÀ"},
	{"day": "Wednesday 10. 6.", "stage": "E2 Stage", "start": "16:25", "end": "17:10", "band_name": "LENKA DUSILOVÁ: LD_50 A HOST DAVID KOLLER"},
	{"day": "Wednesday 10. 6.", "stage": "E2 Stage", "start": "18:05", "end": "18:50", "band_name": "H-BLOCKX"},
	{"day": "Wednesday 10. 6.", "stage": "E2 Stage", "start": "20:00", "end": "21:00", "band_name": "DIE SPITZ"},
	{"day": "Wednesday 10. 6.", "stage": "E2 Stage", "start": "23:00", "end": "00:00", "band_name": "TRIVIUM"},
	{"day": "Wednesday 10. 6.", "stage": "E2 Stage", "start": "00:30", "end": "01:30", "band_name": "JOEY VALENCE & BRAE"},
	{"day": "Wednesday 10. 6.", "stage": "Petr Svoboda Stage", "start": "12:20", "end": "13:00", "band_name": "BYT ČÍSLO 4"},
	{"day": "Wednesday 10. 6.", "stage": "Petr Svoboda Stage", "start": "13:55", "end": "14:40", "band_name": "MOUTH CULTURE"},
	{"day": "Wednesday 10. 6.", "stage": "Petr Svoboda Stage", "start": "15:35", "end": "16:20", "band_name": "NEVERTEL"},
	{"day": "Wednesday 10. 6.", "stage": "Petr Svoboda Stage", "start": "17:15", "end": "18:00", "band_name": "GURRIERS"},
	{"day": "Wednesday 10. 6.", "stage": "Petr Svoboda Stage", "start": "18:55", "end": "19:40", "band_name": "WATER FROM YOUR EYES"},
	{"day": "Wednesday 10. 6.", "stage": "Petr Svoboda Stage", "start": "21:45", "end": "22:30", "band_name": "TCHERT"},
	{"day": "Wednesday 10. 6.", "stage": "ČT art Stage", "start": "12:45", "end": "13:30", "band_name": "CIRCUS BROTHERS"},
	{"day": "Wednesday 10. 6.", "stage": "ČT art Stage", "start": "14:15", "end": "15:00", "band_name": "TOLSTOYS"},
	{"day": "Wednesday 10. 6.", "stage": "ČT art Stage", "start": "15:45", "end": "16:30", "band_name": "ECCA VANDAL"},
	{"day": "Wednesday 10. 6.", "stage": "ČT art Stage", "start": "17:15", "end": "18:00", "band_name": "AS IT IS"},
	{"day": "Wednesday 10. 6.", "stage": "ČT art Stage", "start": "18:45", "end": "19:30", "band_name": "TX2"},
	{"day": "Wednesday 10. 6.", "stage": "ČT art Stage", "start": "20:10", "end": "20:55", "band_name": "GENESIS OWUSU"},
	{"day": "Wednesday 10. 6.", "stage": "ČT art Stage", "start": "21:35", "end": "22:20", "band_name": "BOUNDARIES"},
	{"day": "Wednesday 10. 6.", "stage": "ČT art Stage", "start": "23:00", "end": "00:00", "band_name": "THROWN"},
	{"day": "Wednesday 10. 6.", "stage": "ČT art Stage", "start": "00:30", "end": "02:00", "band_name": "ALYX HOLCOMBE"},
	{"day": "Wednesday 10. 6.", "stage": "Reflex Stage", "start": "12:05", "end": "12:50", "band_name": "PLANETROX 2026"},
	{"day": "Wednesday 10. 6.", "stage": "Reflex Stage", "start": "13:45", "end": "14:30", "band_name": "PLANETROX 2026"},
	{"day": "Wednesday 10. 6.", "stage": "Reflex Stage", "start": "15:55", "end": "16:40", "band_name": "PLANETROX 2026"},
	{"day": "Wednesday 10. 6.", "stage": "Reflex Stage", "start": "18:45", "end": "19:30", "band_name": "PLANETROX 2026"},
	{"day": "Wednesday 10. 6.", "stage": "Reflex Stage", "start": "21:15", "end": "22:00", "band_name": "MØNØDREAM"},
	{"day": "Wednesday 10. 6.", "stage": "Reflex Stage", "start": "00:00", "end": "01:00", "band_name": "ZUZANĚ NAVAROVÉ DO NEBES"},
	{"day": "Wednesday 10. 6.", "stage": "EcoFlow Stage", "start": "11:35", "end": "12:15", "band_name": "SPECIAL GUEST BY MASTERCARD"},
	{"day": "Wednesday 10. 6.", "stage": "EcoFlow Stage", "start": "12:45", "end": "13:25", "band_name": "BAZZOOKAS"},
	{"day": "Wednesday 10. 6.", "stage": "EcoFlow Stage", "start": "14:40", "end": "15:20", "band_name": "CHERRYHOLT"},
	{"day": "Wednesday 10. 6.", "stage": "EcoFlow Stage", "start": "17:10", "end": "17:55", "band_name": "KAŠPÁREK V ROHLÍKU"},
	{"day": "Wednesday 10. 6.", "stage": "EcoFlow Stage", "start": "19:30", "end": "20:10", "band_name": "NÉSTOR ÁLVAREZ & ORIGINAL GRAVITY ALLSTARS"},
	{"day": "Wednesday 10. 6.", "stage": "EcoFlow Stage", "start": "20:40", "end": "21:20", "band_name": "SUPERMODEL*"},
	{"day": "Wednesday 10. 6.", "stage": "EcoFlow Stage", "start": "23:15", "end": "00:45", "band_name": "PENDL"},
	{"day": "Wednesday 10. 6.", "stage": "Karaoke Stage", "start": "10:10", "end": "10:50", "band_name": "SPECIAL GUEST BY MASTERCARD"},
	{"day": "Thursday 11. 6.", "stage": "Mastercard Stage", "start": "12:15", "end": "13:00", "band_name": "SET IT OFF"},
	{"day": "Thursday 11. 6.", "stage": "Mastercard Stage", "start": "13:55", "end": "14:40", "band_name": "THE PLOT IN YOU"},
	{"day": "Thursday 11. 6.", "stage": "Mastercard Stage", "start": "15:50", "end": "16:50", "band_name": "BREAKING BENJAMIN"},
	{"day": "Thursday 11. 6.", "stage": "Mastercard Stage", "start": "18:10", "end": "19:25", "band_name": "BABYMETAL"},
	{"day": "Thursday 11. 6.", "stage": "Mastercard Stage", "start": "21:30", "end": "23:00", "band_name": "LIMP BIZKIT"},
	{"day": "Thursday 11. 6.", "stage": "Rock for People Stage", "start": "11:25", "end": "12:10", "band_name": "THORNHILL"},
	{"day": "Thursday 11. 6.", "stage": "Rock for People Stage", "start": "13:05", "end": "13:50", "band_name": "WOHNOUT"},
	{"day": "Thursday 11. 6.", "stage": "Rock for People Stage", "start": "14:45", "end": "15:45", "band_name": "SOCIAL DISTORTION"},
	{"day": "Thursday 11. 6.", "stage": "Rock for People Stage", "start": "16:55", "end": "17:55", "band_name": "ALL TIME LOW"},
	{"day": "Thursday 11. 6.", "stage": "Rock for People Stage", "start": "19:40", "end": "21:10", "band_name": "PAPA ROACH"},
	{"day": "Thursday 11. 6.", "stage": "E2 Stage", "start": "11:25", "end": "12:10", "band_name": "MC GEY & LIVE BAND"},
	{"day": "Thursday 11. 6.", "stage": "E2 Stage", "start": "13:05", "end": "13:50", "band_name": "LETLIVE."},
	{"day": "Thursday 11. 6.", "stage": "E2 Stage", "start": "14:45", "end": "15:30", "band_name": "CATCH YOUR BREATH"},
	{"day": "Thursday 11. 6.", "stage": "E2 Stage", "start": "16:25", "end": "17:10", "band_name": "BLOOD INCANTATION"},
	{"day": "Thursday 11. 6.", "stage": "E2 Stage", "start": "18:05", "end": "18:50", "band_name": "DESTROY BOYS"},
	{"day": "Thursday 11. 6.", "stage": "E2 Stage", "start": "19:50", "end": "20:50", "band_name": "YARD ACT"},
	{"day": "Thursday 11. 6.", "stage": "E2 Stage", "start": "23:00", "end": "00:00", "band_name": "THE ALL-AMERICAN REJECTS"},
	{"day": "Thursday 11. 6.", "stage": "E2 Stage", "start": "00:45", "end": "01:45", "band_name": "GLEB"},
	{"day": "Thursday 11. 6.", "stage": "Petr Svoboda Stage", "start": "12:15", "end": "13:00", "band_name": "BANKS ARCADE"},
	{"day": "Thursday 11. 6.", "stage": "Petr Svoboda Stage", "start": "13:55", "end": "14:40", "band_name": "THE PRETTY WILD"},
	{"day": "Thursday 11. 6.", "stage": "Petr Svoboda Stage", "start": "15:35", "end": "16:20", "band_name": "RADIO FREE ALICE"},
	{"day": "Thursday 11. 6.", "stage": "Petr Svoboda Stage", "start": "17:15", "end": "18:00", "band_name": "LAST TRAIN"},
	{"day": "Thursday 11. 6.", "stage": "Petr Svoboda Stage", "start": "18:55", "end": "19:40", "band_name": "BARNS COURTNEY"},
	{"day": "Thursday 11. 6.", "stage": "Petr Svoboda Stage", "start": "20:50", "end": "21:35", "band_name": "DEKI ALEM"},
	{"day": "Thursday 11. 6.", "stage": "Petr Svoboda Stage", "start": "22:15", "end": "23:00", "band_name": "DIZZLOVE"},
	{"day": "Thursday 11. 6.", "stage": "ČT art Stage", "start": "17:20", "end": "18:05", "band_name": "QUICKSAND"},
	{"day": "Thursday 11. 6.", "stage": "ČT art Stage", "start": "18:45", "end": "19:30", "band_name": "JAMES COLE & IDEA"},
	{"day": "Thursday 11. 6.", "stage": "ČT art Stage", "start": "20:10", "end": "20:55", "band_name": "ETTA MARCUS"},
	{"day": "Thursday 11. 6.", "stage": "ČT art Stage", "start": "21:35", "end": "22:20", "band_name": "VLTAVA"},
	{"day": "Thursday 11. 6.", "stage": "ČT art Stage", "start": "23:00", "end": "00:00", "band_name": "MELROSE AVENUE"},
	{"day": "Thursday 11. 6.", "stage": "Reflex Stage", "start": "18:45", "end": "19:30", "band_name": "FRANKIE & THE DEADBEATS"},
	{"day": "Thursday 11. 6.", "stage": "Reflex Stage", "start": "21:20", "end": "22:05", "band_name": "THE FIALKY"},
	{"day": "Thursday 11. 6.", "stage": "Reflex Stage", "start": "23:15", "end": "00:15", "band_name": "DESADE X DENOI"},
	{"day": "Thursday 11. 6.", "stage": "Reflex Stage", "start": "00:30", "end": "02:00", "band_name": "KLUBOVNA AFTERPARTY"},
	{"day": "Thursday 11. 6.", "stage": "EcoFlow Stage", "start": "14:55", "end": "15:35", "band_name": "INDOOR FOXES"},
	{"day": "Thursday 11. 6.", "stage": "EcoFlow Stage", "start": "17:15", "end": "17:55", "band_name": "WÓĎA A DEKORACE"},
	{"day": "Thursday 11. 6.", "stage": "EcoFlow Stage", "start": "19:30", "end": "20:10", "band_name": "WYFE"},
	{"day": "Thursday 11. 6.", "stage": "EcoFlow Stage", "start": "20:40", "end": "21:20", "band_name": "CINTORINI"},
	{"day": "Thursday 11. 6.", "stage": "EcoFlow Stage", "start": "23:00", "end": "23:45", "band_name": "SPECIAL GUEST BY MASTERCARD"},
	{"day": "Thursday 11. 6.", "stage": "Karaoke Stage", "start": "10:10", "end": "10:50", "band_name": "SPECIAL GUEST BY MASTERCARD"},
	{"day": "Friday 12. 6.", "stage": "Mastercard Stage", "start": "13:20", "end": "14:05", "band_name": "BASEMENT"},
	{"day": "Friday 12. 6.", "stage": "Mastercard Stage", "start": "15:00", "end": "15:45", "band_name": "BEN CRISTOVAO"},
	{"day": "Friday 12. 6.", "stage": "Mastercard Stage", "start": "16:40", "end": "17:40", "band_name": "TOM MORELLO"},
	{"day": "Friday 12. 6.", "stage": "Mastercard Stage", "start": "19:00", "end": "20:15", "band_name": "A DAY TO REMEMBER"},
	{"day": "Friday 12. 6.", "stage": "Mastercard Stage", "start": "21:45", "end": "23:15", "band_name": "BRING ME THE HORIZON"},
	{"day": "Friday 12. 6.", "stage": "Rock for People Stage", "start": "12:30", "end": "13:15", "band_name": "SOUTH ARCADE"},
	{"day": "Friday 12. 6.", "stage": "Rock for People Stage", "start": "14:10", "end": "14:55", "band_name": "GATECREEPER"},
	{"day": "Friday 12. 6.", "stage": "Rock for People Stage", "start": "15:50", "end": "16:35", "band_name": "DINOSAUR PILE-UP"},
	{"day": "Friday 12. 6.", "stage": "Rock for People Stage", "start": "17:45", "end": "18:45", "band_name": "BILMURI"},
	{"day": "Friday 12. 6.", "stage": "Rock for People Stage", "start": "20:30", "end": "21:30", "band_name": "WOLF ALICE"},
	{"day": "Friday 12. 6.", "stage": "Rock for People Stage", "start": "23:30", "end": "01:00", "band_name": "THREE DAYS GRACE"},
	{"day": "Friday 12. 6.", "stage": "E2 Stage", "start": "12:00", "end": "12:45", "band_name": "EGO KILL TALENT"},
	{"day": "Friday 12. 6.", "stage": "E2 Stage", "start": "13:40", "end": "14:25", "band_name": "TRASH BOAT"},
	{"day": "Friday 12. 6.", "stage": "E2 Stage", "start": "15:20", "end": "16:05", "band_name": "DYING WISH"},
	{"day": "Friday 12. 6.", "stage": "E2 Stage", "start": "17:00", "end": "17:45", "band_name": "JIŘÍ PAVLICA & HRADIŠŤAN"},
	{"day": "Friday 12. 6.", "stage": "E2 Stage", "start": "18:40", "end": "19:25", "band_name": "IVRI"},
	{"day": "Friday 12. 6.", "stage": "E2 Stage", "start": "20:30", "end": "21:30", "band_name": "HIGH VIS"},
	{"day": "Friday 12. 6.", "stage": "E2 Stage", "start": "00:00", "end": "01:10", "band_name": "TATA BOJS"},
	{"day": "Friday 12. 6.", "stage": "E2 Stage", "start": "01:55", "end": "03:00", "band_name": "SVDDEN DEATH"},
	{"day": "Friday 12. 6.", "stage": "Petr Svoboda Stage", "start": "11:25", "end": "11:55", "band_name": "KLAMAT"},
	{"day": "Friday 12. 6.", "stage": "Petr Svoboda Stage", "start": "12:50", "end": "13:35", "band_name": "THE CLAUSE"},
	{"day": "Friday 12. 6.", "stage": "Petr Svoboda Stage", "start": "14:30", "end": "15:15", "band_name": "ANKOR"},
	{"day": "Friday 12. 6.", "stage": "Petr Svoboda Stage", "start": "16:10", "end": "16:55", "band_name": "DAVE LOFTS"},
	{"day": "Friday 12. 6.", "stage": "Petr Svoboda Stage", "start": "17:50", "end": "18:35", "band_name": "PRIVATE SCHOOL"},
	{"day": "Friday 12. 6.", "stage": "Petr Svoboda Stage", "start": "19:45", "end": "20:30", "band_name": "UNPEOPLE"},
	{"day": "Friday 12. 6.", "stage": "Petr Svoboda Stage", "start": "21:30", "end": "22:15", "band_name": "KVIETAH"},
	{"day": "Friday 12. 6.", "stage": "Petr Svoboda Stage", "start": "23:15", "end": "00:00", "band_name": "VOWER"},
	{"day": "Friday 12. 6.", "stage": "Petr Svoboda Stage", "start": "01:10", "end": "01:55", "band_name": "GLARE"},
	{"day": "Friday 12. 6.", "stage": "ČT art Stage", "start": "19:20", "end": "20:05", "band_name": "LOTTERY WINNERS"},
	{"day": "Friday 12. 6.", "stage": "ČT art Stage", "start": "20:45", "end": "21:30", "band_name": "ZERO 9:36"},
	{"day": "Friday 12. 6.", "stage": "ČT art Stage", "start": "22:10", "end": "22:55", "band_name": "FVLCRVM"},
	{"day": "Friday 12. 6.", "stage": "ČT art Stage", "start": "23:35", "end": "00:20", "band_name": "GAEREA"},
	{"day": "Friday 12. 6.", "stage": "ČT art Stage", "start": "01:00", "end": "02:00", "band_name": "VENTOLIN"},
	{"day": "Friday 12. 6.", "stage": "Reflex Stage", "start": "18:45", "end": "19:30", "band_name": "STARTÉR: TEIGE"},
	{"day": "Friday 12. 6.", "stage": "Reflex Stage", "start": "22:45", "end": "23:30", "band_name": "MARIE APRIL"},
	{"day": "Friday 12. 6.", "stage": "Reflex Stage", "start": "00:30", "end": "01:30", "band_name": "MADFACE"},
	{"day": "Friday 12. 6.", "stage": "Reflex Stage", "start": "01:30", "end": "03:00", "band_name": "LEDUY + BEA"},
	{"day": "Friday 12. 6.", "stage": "EcoFlow Stage", "start": "15:50", "end": "16:30", "band_name": "ANY YOUNG MECHANIC"},
	{"day": "Friday 12. 6.", "stage": "EcoFlow Stage", "start": "17:40", "end": "18:25", "band_name": "UE"},
	{"day": "Friday 12. 6.", "stage": "EcoFlow Stage", "start": "20:30", "end": "21:15", "band_name": "FVCK_KVLT"},
	{"day": "Friday 12. 6.", "stage": "EcoFlow Stage", "start": "23:30", "end": "00:30", "band_name": "NOISY POTS"},
	{"day": "Friday 12. 6.", "stage": "Karaoke Stage", "start": "10:10", "end": "10:50", "band_name": "SPECIAL GUEST BY MASTERCARD"},
	{"day": "Saturday 13. 6.", "stage": "Mastercard Stage", "start": "14:00", "end": "14:45", "band_name": "KID KAPICHI"},
	{"day": "Saturday 13. 6.", "stage": "Mastercard Stage", "start": "15:40", "end": "16:25", "band_name": "ALESSI ROSE"},
	{"day": "Saturday 13. 6.", "stage": "Mastercard Stage", "start": "17:20", "end": "18:20", "band_name": "DON BROCO"},
	{"day": "Saturday 13. 6.", "stage": "Mastercard Stage", "start": "19:30", "end": "20:45", "band_name": "NOTHING BUT THIEVES"},
	{"day": "Saturday 13. 6.", "stage": "Mastercard Stage", "start": "22:10", "end": "23:40", "band_name": "HALSEY"},
	{"day": "Saturday 13. 6.", "stage": "Rock for People Stage", "start": "13:10", "end": "13:55", "band_name": "POLICE SYMPHONY ORCHESTRA"},
	{"day": "Saturday 13. 6.", "stage": "Rock for People Stage", "start": "14:50", "end": "15:35", "band_name": "BURY TOMORROW"},
	{"day": "Saturday 13. 6.", "stage": "Rock for People Stage", "start": "16:30", "end": "17:15", "band_name": "SOFIAN MEDJMEDJ"},
	{"day": "Saturday 13. 6.", "stage": "Rock for People Stage", "start": "18:25", "end": "19:25", "band_name": "YONAKA"},
	{"day": "Saturday 13. 6.", "stage": "Rock for People Stage", "start": "20:50", "end": "21:50", "band_name": "BLACKBEAR"},
	{"day": "Saturday 13. 6.", "stage": "Rock for People Stage", "start": "23:45", "end": "01:00", "band_name": "WITHIN TEMPTATION"},
	{"day": "Saturday 13. 6.", "stage": "E2 Stage", "start": "12:30", "end": "13:15", "band_name": "CALVA LOUISE"},
	{"day": "Saturday 13. 6.", "stage": "E2 Stage", "start": "14:10", "end": "14:55", "band_name": "BERLIN MANSON"},
	{"day": "Saturday 13. 6.", "stage": "E2 Stage", "start": "15:50", "end": "16:35", "band_name": "I KILLED THE PROM QUEEN"},
	{"day": "Saturday 13. 6.", "stage": "E2 Stage", "start": "17:30", "end": "18:15", "band_name": "MALEVOLENCE"},
	{"day": "Saturday 13. 6.", "stage": "E2 Stage", "start": "19:10", "end": "19:55", "band_name": "PRESIDENT"},
	{"day": "Saturday 13. 6.", "stage": "E2 Stage", "start": "20:50", "end": "21:50", "band_name": "SILENT PLANET"},
	{"day": "Saturday 13. 6.", "stage": "E2 Stage", "start": "00:00", "end": "01:00", "band_name": "BABYSHAMBLES"},
	{"day": "Saturday 13. 6.", "stage": "E2 Stage", "start": "01:45", "end": "03:00", "band_name": "DELTA HEAVY"},
	{"day": "Saturday 13. 6.", "stage": "Petr Svoboda Stage", "start": "11:45", "end": "12:30", "band_name": "JET8"},
	{"day": "Saturday 13. 6.", "stage": "Petr Svoboda Stage", "start": "13:20", "end": "14:05", "band_name": "GRADE 2"},
	{"day": "Saturday 13. 6.", "stage": "Petr Svoboda Stage", "start": "15:00", "end": "15:45", "band_name": "WESTSIDE COWBOY"},
	{"day": "Saturday 13. 6.", "stage": "Petr Svoboda Stage", "start": "16:40", "end": "17:25", "band_name": "OVERPASS"},
	{"day": "Saturday 13. 6.", "stage": "Petr Svoboda Stage", "start": "18:20", "end": "19:05", "band_name": "KEO"},
	{"day": "Saturday 13. 6.", "stage": "Petr Svoboda Stage", "start": "20:00", "end": "20:45", "band_name": "SPILL TAB"},
	{"day": "Saturday 13. 6.", "stage": "Petr Svoboda Stage", "start": "21:50", "end": "22:35", "band_name": "THE COMPLICATION"},
	{"day": "Saturday 13. 6.", "stage": "Petr Svoboda Stage", "start": "23:15", "end": "00:00", "band_name": "REZN"},
	{"day": "Saturday 13. 6.", "stage": "Petr Svoboda Stage", "start": "01:00", "end": "01:45", "band_name": "ALT BLK ERA"},
	{"day": "Saturday 13. 6.", "stage": "ČT art Stage", "start": "19:00", "end": "19:45", "band_name": "VENUS GRRRLS"},
	{"day": "Saturday 13. 6.", "stage": "ČT art Stage", "start": "20:30", "end": "21:15", "band_name": "SNAYX"},
	{"day": "Saturday 13. 6.", "stage": "ČT art Stage", "start": "21:55", "end": "22:40", "band_name": "THE 900: TONY HAWK'S PRO SKATER COVER BAND"},
	{"day": "Saturday 13. 6.", "stage": "ČT art Stage", "start": "23:20", "end": "00:20", "band_name": "HOLYWATR"},
	{"day": "Saturday 13. 6.", "stage": "ČT art Stage", "start": "01:00", "end": "02:00", "band_name": "THE FUNERAL PORTRAIT"},
	{"day": "Saturday 13. 6.", "stage": "Reflex Stage", "start": "19:25", "end": "20:10", "band_name": "OVERGROWN"},
	{"day": "Saturday 13. 6.", "stage": "Reflex Stage", "start": "21:50", "end": "22:35", "band_name": "HOPES"},
	{"day": "Saturday 13. 6.", "stage": "Reflex Stage", "start": "23:30", "end": "00:15", "band_name": "POST-HUDBA"},
	{"day": "Saturday 13. 6.", "stage": "Reflex Stage", "start": "01:15", "end": "03:00", "band_name": "ŠATYSVLEČKOU"},
	{"day": "Saturday 13. 6.", "stage": "EcoFlow Stage", "start": "16:30", "end": "17:10", "band_name": "ACID ROW"},
	{"day": "Saturday 13. 6.", "stage": "EcoFlow Stage", "start": "18:20", "end": "19:05", "band_name": "SIMON OPP"},
	{"day": "Saturday 13. 6.", "stage": "EcoFlow Stage", "start": "21:25", "end": "22:10", "band_name": "ELEKTRÏCK MANN"},
	{"day": "Saturday 13. 6.", "stage": "EcoFlow Stage", "start": "23:45", "end": "00:45", "band_name": "MINDGAZE"},
	{"day": "Saturday 13. 6.", "stage": "Karaoke Stage", "start": "10:10", "end": "10:50", "band_name": "SPECIAL GUEST BY MASTERCARD"},
	{"day": "Sunday 14. 6.", "stage": "Mastercard Stage", "start": "14:15", "end": "15:00", "band_name": "LOATHE"},
	{"day": "Sunday 14. 6.", "stage": "Mastercard Stage", "start": "15:55", "end": "16:40", "band_name": "QUEENSRŸCHE"},
	{"day": "Sunday 14. 6.", "stage": "Mastercard Stage", "start": "17:50", "end": "18:50", "band_name": "ALTER BRIDGE"},
	{"day": "Sunday 14. 6.", "stage": "Mastercard Stage", "start": "20:40", "end": "22:50", "band_name": "IRON MAIDEN"},
	{"day": "Sunday 14. 6.", "stage": "Rock for People Stage", "start": "13:25", "end": "14:10", "band_name": "BLACKGOLD"},
	{"day": "Sunday 14. 6.", "stage": "Rock for People Stage", "start": "15:05", "end": "15:50", "band_name": "ALICE & DAN BÁRTA"},
	{"day": "Sunday 14. 6.", "stage": "Rock for People Stage", "start": "16:45", "end": "17:45", "band_name": "KNOCKED LOOSE"},
	{"day": "Sunday 14. 6.", "stage": "Rock for People Stage", "start": "19:05", "end": "20:20", "band_name": "SAXON"},
	{"day": "Sunday 14. 6.", "stage": "E2 Stage", "start": "13:10", "end": "13:55", "band_name": "THE MOLOTOVS"},
	{"day": "Sunday 14. 6.", "stage": "E2 Stage", "start": "14:40", "end": "15:25", "band_name": "MILITARIE GUN"},
	{"day": "Sunday 14. 6.", "stage": "E2 Stage", "start": "16:10", "end": "16:55", "band_name": "MAN WITH A MISSION"},
	{"day": "Sunday 14. 6.", "stage": "E2 Stage", "start": "17:45", "end": "18:30", "band_name": "SLEEP THEORY"},
	{"day": "Sunday 14. 6.", "stage": "E2 Stage", "start": "19:20", "end": "20:20", "band_name": "ALEXISONFIRE"},
	{"day": "Sunday 14. 6.", "stage": "E2 Stage", "start": "23:00", "end": "00:00", "band_name": "GOD IS AN ASTRONAUT"},
	{"day": "Sunday 14. 6.", "stage": "Petr Svoboda Stage", "start": "13:55", "end": "14:40", "band_name": "CHRPY"},
	{"day": "Sunday 14. 6.", "stage": "Petr Svoboda Stage", "start": "15:25", "end": "16:10", "band_name": "GRIDIRON"},
	{"day": "Sunday 14. 6.", "stage": "Petr Svoboda Stage", "start": "16:55", "end": "17:40", "band_name": "THE LILACS"},
	{"day": "Sunday 14. 6.", "stage": "Petr Svoboda Stage", "start": "18:30", "end": "19:15", "band_name": "LINKA MOJA"},
	{"day": "Sunday 14. 6.", "stage": "Petr Svoboda Stage", "start": "20:20", "end": "21:05", "band_name": "REFLECTIONS OF KARMA"},
	{"day": "Sunday 14. 6.", "stage": "Petr Svoboda Stage", "start": "22:00", "end": "22:45", "band_name": "MIDRIFT"},
	{"day": "Sunday 14. 6.", "stage": "ČT art Stage", "start": "18:45", "end": "19:30", "band_name": "VIANOVA"},
	{"day": "Sunday 14. 6.", "stage": "ČT art Stage", "start": "21:00", "end": "21:45", "band_name": "RAIN CITY DRIVE"},
	{"day": "Sunday 14. 6.", "stage": "ČT art Stage", "start": "23:15", "end": "00:00", "band_name": "SCENE QUEEN"},
	{"day": "Sunday 14. 6.", "stage": "Reflex Stage", "start": "17:45", "end": "18:30", "band_name": "COLD MEAT PARTY"},
	{"day": "Sunday 14. 6.", "stage": "Reflex Stage", "start": "20:15", "end": "21:00", "band_name": "WHITE FRUIT HONEY"},
	{"day": "Sunday 14. 6.", "stage": "Reflex Stage", "start": "23:15", "end": "00:00", "band_name": "SAFARI DUO (80S & 90S ROCK)"},
	{"day": "Sunday 14. 6.", "stage": "EcoFlow Stage", "start": "13:25", "end": "14:05", "band_name": "FROZEN POPPYHEAD"},
	{"day": "Sunday 14. 6.", "stage": "EcoFlow Stage", "start": "15:15", "end": "15:55", "band_name": "LUNARSEA"},
	{"day": "Sunday 14. 6.", "stage": "EcoFlow Stage", "start": "17:10", "end": "17:50", "band_name": "FLORENCE BLACK"},
	{"day": "Sunday 14. 6.", "stage": "EcoFlow Stage", "start": "19:35", "end": "20:15", "band_name": "THE ATAVISTS"},
	{"day": "Sunday 14. 6.", "stage": "EcoFlow Stage", "start": "23:15", "end": "00:00", "band_name": "N.O.H.A."},
	{"day": "Sunday 14. 6.", "stage": "Karaoke Stage", "start": "10:10", "end": "10:50", "band_name": "HOLLOW SUNS"},
	{"day": "Sunday 14. 6.", "stage": "Karaoke Stage", "start": "11:30", "end": "12:10", "band_name": "EXCIDE"}
]
